version: '3.8'

services:
  db:
    image: postgres:16.1-alpine
    restart: on-failure
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: url_shortener
      POSTGRES_PASSWORD: url_shortener
      POSTGRES_DB: url_shortener
      TZ: GMT+3
    healthcheck:
      test: pg_isready -U url_shortener -d url_shortener
      interval: 30s
      timeout: 3s
      retries: 3